<html>
<head>
<title>Portada de Lab. de Programacion Web </title>
</head>
<p style="font-size: 30px ">Portada de Lab. de Programacion Web<p>
<p style="font-size: x-large">M.I.I Carlos Adrian Perez Cortez<p>
<font face="Comic Sans MS,Arial,Verdana">Datos de Equipo:</p>
<font face="Comic Sans MS,Arial,Verdana">Deisy Jazmin Villalobos Lucio Matr:1907104 Carrera:IAS</p>
<font face="Comic Sans MS,Arial,Verdana">Gian Karlo Jocsan Estrada Martinez Matr:1801149 Carrera:ITS</p>
<font face="Comic Sans MS,Arial,Verdana">Alan Mauricio Reyna Rodriguez Matr:1917008 Carrera:ITS</p>
<font face="Comic Sans MS,Arial,Verdana">Luis Fernando Luna Cañamar Matr:1758362 Carrera:ITS</p>
<font face="Comic Sans MS,Arial,Verdana">Alan Diaz Pinto Matr:1921919 Carrera:IAS</p>
<body> 

